### ISSUE TITLE
Android 10 无法使用

### ISSUE THREAD

**Issue by zlmkaka** [ccc920123/LicensePlateDemo#2]
Unable to create service com.kernal.plateid.PlateRecogService: Caused by: java.lang.SecurityException: getDeviceId: The user 10356 does not meet the requirements to access device identifiers.

**Comment by ccc920123** [comment]
构建项目采用targetSdkVersion 28  compileSdkVersion28  就不会检查DeviceId

**Comment by zlmkaka** [comment]
我之前改了下可以用了

**Comment by impl1874** [comment]
https://github.com/oasisfeng/condom

这个也蛮好的，在Android 13使用正常
